name: GitHub Actions Demo
# name: GitHub Actions Demo
# name: github-actions-demo.yml

# on every push to main branch, except when changes to .github folder
# on every pull request with main as the base branch
# Every Sun at 6:15
# Manually

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

# Create a job that runs on Ubuntu-latest
# output the workflow event trigger
# output the repo branch name
# list all files

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "The job was triggered by event: ${{ github.event_name }}"
        echo "The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repo
        run: | 
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
