name: Hello World Docker Action

on:
  workflow_dispatch:

jobs:
  run-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run custom Docker action
        uses: ./hello-world-docker-action/action.yml
        with:
          who-to-greet: Monica
